POST http://localhost:3003/api/blogs
//POST https://phonebook-backend-cool-waterfall-1089.fly.dev/api/persons
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "user": "67a969a1a984f0ce0b582e55"
}