POST http://localhost:3003/api/blogs
//POST https://phonebook-backend-cool-waterfall-1089.fly.dev/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2N2E5NjlhMWE5ODRmMGNlMGI1ODJlNTUiLCJpYXQiOjE3Mzk3NjEyODIsImV4cCI6MTczOTc2NDg4Mn0.eDSKzTHJ2QiTaxGSPTMjtVklpmqAaXEBn6xHtbEUHnA

{
    "title": "React patterns Review",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": "7",
    "user": "67a969a1a984f0ce0b582e55"
}